# Generated by Django 2.2.2 on 2019-09-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_booking_aaa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='aaa',
        ),
    ]
